config-dist.php
Trying to edit the fields in a $CFT variable gave weird errors since there is no $CFT object.
=> Update config-dist.php to correct error

dev.php
What was happening was that all of my attempts at using keys other than `12345` would default back to `12345`. After inspection of `dev.php` I saw that tsugi was not updating the `$key` variable from `12345` to the what the user passed in in the `$_REQUEST`. So after making this change, tsugi worked with my LTI components that needed specific keys / secrets.
Thanks,
Josh Harington
=> DEV.php update to persist user key

admin/install/repos_json.php
Hi Charles,
The bit of code just adds a name to the tools that are not defined in the **tsugitools** repo, not major; improves the display a little.
Kind regards,
Corné Oosthuizen
=> Extract additional tools name from GitHub URL.

admin/lti/database.php
My AWS Lightsail/Bitnami hosting borked on the db upgrade here and this fixed it. Not sure if it's a bug or not, but thought I'd pass it along and see.
=> fixed possible bug in creating lti_domain DB table updated_at

config-dist.php
Provides an example debug function which has proven critical in other PHP projects I've written / used in order to debug initial install / deep level admin areas which can throw difficult to debug 500 errors otherwise. This forces the buffer to return a response as to what the error was. Either placing it in this file as an example of throwing it into the documentation might be helpful long term.
=> Sample for the config-dist file to help w/ deep level 500 errors

config-dist.php
If config.php is symlinked instead of directly included in the local directory it's self-discovery default function for $dirroot will resolve incorrectly causing a 500 error. This adds a simple comment noting this.
=> note about symbolically linking the config.php file

vendor/tsugi/lib/src/Core/Entity.php, vendor/tsugi/lib/src/Core/JsonTrait.php, vendor/tsugi/lib/src/Core/User.php
Hi Chuck,
In the development of a few tools we needed a place to store a a value or two that are important to a particular user and should be cross tool usable. The other core object contain a settings column, but without changing the database this seems to be a good solution.
Yes, the value is then accessible by other (outside) tools and may even be overwritten by them 😣 
Hope this is what you had in mind for this column - more general settings/variable storage.
All the best,
Corné
=> Added access to the json column class user (lti_user)

admin/rachet.php, config-dist.php, vendor/tsugi/lib/src/Core/WebSocket.php
Some folks may want to setup their websocket using proxy_wstunnel.  In such a case the rachet server may need to listen on a different port than http/https requests.
=> option to use apache2 mod_proxy_tunnel for websocket

vendor/tsugi/lib/src/UI/Output.php
Hopefully, this change won't cause any problems for other Tsugi tools. Our new app design (email and info coming soon) needs a class to target to auto-hide the alert banners and adding a bootstrap container div around the alert content allowed for additional styling in our tool. The functionality remains the same.
=> Change banner alert styling for new app design

vendor/tsugi/lib/src/Util/LTI.php
If using roster feature in a tool a warning will show in the Tsugi tool that says,
"Deprecated: The each() function is deprecated. This message will be suppressed on
further calls in /.../vendor/tsugi/lib/src/Util/LTI.php on line 684"
=> Each() is deprecated in PHP 7.2 so replace with foreach

admin/install/database.php
In MySQL 8, "rank" is a reserved word and shouldn't be used as a column name.
This can still be done if you use backticks to escape the name.
=> Escape reserved word rank with backticks

vendor/tsugi/lib/src/Core/LTIX.php, vendor/tsugi/lib/src/Util/LTI.php
So by default this doesn't change any of the standard functionality it adds the option after the page is loaded then by calling:
```
// Handle the Roster
$handledRoster = LTIX::populateRoster(false, true);
```
The lti_user and lti_membership tables are updated with the student roster. 
This should be a considered action because the size of the roster might be quite large and not something to do every time the page loads.
- SimpleXMLElement parse error - utf8_encode added to response function
- Valid Roster->url  before going to all the trouble of getting the membership
- populateRoster function documentation update
- Fixed how the person source id is found and how it is updated in MySQL (using json functions)
- roster insert is false by default
=> Roster information stored in lti_user and lti_membership.

config-dist.php, vendor/koseu/lib/src/Controllers/Topics.php, vendor/koseu/lib/src/Core/Application.php, vendor/koseu/lib/src/Templates/Topics.twig, vendor/tsugi/lib/src/UI/Topics.php
Topics can be created independently from lesson.json in a similar format.
topics.json should be created and set in the config. Topics can consist of the following
{
"title": "Topics Page Title",
"description": "Topics pade description.",
"topics": [
{
"title": "Topic Title",
"description": "Short description shown on render all page",
"category": "Something like Assessment, Engagement, etc.",
"thumbnail": "/thumbnails/example.jpg -- url used as written",
"content": "Longer paragraph or two of framing content shown on render single page.",
"time": "Est.XX min",
"author":  "Example Person<br />University of Somewhere",
"anchor": "unique-anchor",
"videos": [
{
"title": "Title of video",
"youtube": "blahblah"
}
]
}
}
=> Add new Topics option for Koseu

cron/canvas.php, vendor/tsugi/lib/include/pdo.php, vendor/tsugi/lib/src/Util/LTI13.php
There are 3 files that have a PHP string append error in primarily error handling (why it hasn't come up before).
cron/canvas.php
vendor/tsugi/lib/include/pdo.php
vendor/tsugi/lib/src/Util/LTI13.php
=> Issue 138: Fix for String Append in 3 files identified.

Dockerfile, README.md
Looks like this had been updated recently to support PHP 8.1, so just updating the Docker to build off that. Started it up and looks like it works fine.
=> Update Docker to php8.1 and docker compose command

vendor/tsugi/lib/src/Util/U.php
Fix for Issue 146:
Error shown on page:
> Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vhosts/tsugi/vendor/tsugi/lib/src/Util/U.php on line 53
PHP 8.1 deprecates these calls, it does not make them errors. The purpose of deprecation is to give authors advance notice to fix their code, so you and the authors of libraries you use have until PHP 9.0 comes out to fix things.
Fix is:
> public static function htmlent_utf8($string) {
>     return htmlentities($string ?? '',ENT_QUOTES,$encoding = 'UTF-8');
> }
=> Fix for  Deprecated: htmlentities(): Passing null to parameter : Issue #146

lti/store/details.php, lti/store/index.php, lti/store/test.php, store/details.php, store/index.php, store/test.php
One more PR in case it is useful!
This one is for updating the store UI, and it isn't terrible as-is, but it is better with the changes in [the PR I submitted for tsugi-static](https://github.com/tsugiproject/tsugi-static/pull/8). It should also work with the [dark mode PR](https://github.com/tsugiproject/tsugi/pull/156).
Main store page:
- A featured slideshow at the top of the store tied to register.php tool_phase = "new"
- New layout for the tool cards in the store main page
- The filter in the store page filters by tool name
Tool details page:
- Layout rearrangements and styling changes
- Breadcrumb at top leading back to the store
Tool test page:
- Minor styling changes
- Breadcrumbs at the top leading back to the tool details and store
=> Store styling updates

admin/key/keys.php, vendor/tsugi/lib/src/Config/ConfigInfo.php
There are two issues when updating php version to php 8.2.
1. The creation of dynamic properties:
- Error Message: 
- Deprecated: Creation of dynamic property ```Tsugi\Config\ConfigInfo::$slow_query``` is deprecated
- Same error messages for ```$logout_return_url``` and ```$verifypeer```
- The solution is to add these fields to ```ConfigInfo.php```
- **NOTE**: I've included some basic comments while adding these fields in ```ConfigInfo```. Feel free to enhance them further if needed.
2. Passing null to ```strlen()```:
- Error Message:
- Deprecated: strlen(): Passing null to parameter # 1 ($string) of type string is deprecated
- The solution is to use ```!empty()``` instead of ```strlen() > 0``` in the if statement.
=> Fix two issues:

lti/store/details.php, lti/store/test.php, store/details.php, store/test.php
Titles containing non-alphanumeric characters can break the layout or formatting when rendered in breadcrumbs. Escaping them on output with html entities fixes this for existing and future titles.
=> Escape breadcrumb titles

admin/index.php, login.php
Stale session ids can cause premature session expiration after login. Regenerating the session id provides the expected session lifetime, and is also considered best practice for session management.
=> Refresh session lifetime

config-dist.php
Provide option to ignore forwarded IP headers for those not running Tsugi behind a reverse proxy. Defaults to trusting headers, following the principle of least surprise, and not altering default behaviour.
=> Configurable forwarded IPs
